/**
 * Media Data Adapter
 * 
 * Manages the bidirectional mapping between Alphax media storage and Omniclip's
 * hash-based IndexedDB storage system.
 * 
 * Key Responsibilities:
 * - Import files into Omniclip's IndexedDB with hash-based deduplication
 * - Maintain mediaId ↔ file_hash mapping
 * - Sync media deletions between systems
 * - Generate thumbnails and metadata
 */

import type { MediaFile } from '@/types/media';
import type { Media } from '../controllers/controllers/media/controller';
import type { AnyMedia } from '../types/media-types';
import { quick_hash } from '@benev/construct';
import { registerMediaMapping, getFileHash, getMediaId } from './timeline-adapter';

/**
 * Import media file into Omniclip engine
 * 
 * @param mediaFile - Alphax media file
 * @param mediaController - Omniclip media controller
 * @returns File hash used by Omniclip
 */
export async function importMediaToEngine(
  mediaFile: MediaFile,
  mediaController: Media
): Promise<string> {
  // Calculate file hash - quick_hash expects a File object directly
  const hash = await quick_hash(mediaFile.file);

  // Check if file already exists in engine
  const existingFile = await mediaController.get_file(hash);
  if (existingFile) {
    // File already imported, just register mapping
    registerMediaMapping(mediaFile.id, hash);
    return hash;
  }

  // Import file using the Media controller's import_file method
  // This handles all media types internally
  await mediaController.import_file(mediaFile.file);
    registerMediaMapping(mediaFile.id, hash);
    return hash;
}

/**
 * Remove media from engine
 * 
 * @param mediaId - Alphax media ID
 * @param mediaController - Omniclip media controller
 */
export async function removeMediaFromEngine(
  mediaId: string,
  mediaController: Media
): Promise<void> {
  const hash = getFileHash(mediaId);
  
  if (!hash) {
    console.warn(`No hash found for media ID: ${mediaId}`);
    return;
  }

  // Delete from IndexedDB
  await mediaController.delete_file(hash);
}

/**
 * Sync all media files from Alphax to Engine
 * 
 * @param mediaFiles - Array of Alphax media files
 * @param mediaController - Omniclip media controller
 */
export async function syncMediaToEngine(
  mediaFiles: MediaFile[],
  mediaController: Media
): Promise<void> {
  // Import all media files in parallel (with reasonable concurrency)
  const batchSize = 3; // Process 3 files at a time to avoid overwhelming the system
  
  for (let i = 0; i < mediaFiles.length; i += batchSize) {
    const batch = mediaFiles.slice(i, i + batchSize);
    await Promise.all(
      batch.map(mediaFile => 
        importMediaToEngine(mediaFile, mediaController).catch(error => {
          console.error(`Failed to import media ${mediaFile.name}:`, error);
        })
      )
    );
  }
}

/**
 * Get all media from engine and create Alphax media files
 * 
 * @param mediaController - Omniclip media controller
 * @returns Array of Alphax media files
 */
export async function getMediaFromEngine(
  mediaController: Media
): Promise<MediaFile[]> {
  const engineMedia = await mediaController.getImportedFiles();
  const mediaFiles: MediaFile[] = [];

  for (const media of engineMedia) {
    // Check if we have a mapping
    let mediaId = getMediaId(media.hash);
    
    // If no mapping exists, create one
    if (!mediaId) {
      mediaId = `engine-${media.hash.slice(0, 8)}`;
      registerMediaMapping(mediaId, media.hash);
    }

    // Convert engine media to Alphax media
    const mediaFile = engineMediaToAlphax(media, mediaId);
    mediaFiles.push(mediaFile);
  }

  return mediaFiles;
}

/**
 * Convert engine media to Alphax media file
 */
function engineMediaToAlphax(media: AnyMedia, mediaId: string): MediaFile {
  // Extract filename from file object or generate from hash
  const fileName = media.file.name || `media-${media.hash.slice(0, 8)}`;
  
  const baseMedia = {
    id: mediaId,
    name: fileName,
    file: media.file,
  };

  if (media.kind === 'video') {
    return {
      ...baseMedia,
      type: 'video' as const,
      duration: media.duration,
      fps: media.fps,
      thumbnailUrl: undefined, // Will be generated by Alphax if needed
    };
  }

  if (media.kind === 'audio') {
    return {
      ...baseMedia,
      type: 'audio' as const,
    };
  }

  if (media.kind === 'image') {
    return {
      ...baseMedia,
      type: 'image' as const,
    };
  }

  throw new Error(`Unknown media kind: ${(media as AnyMedia).kind}`);
}

/**
 * Check if media file exists in engine
 * 
 * @param mediaId - Alphax media ID
 * @param mediaController - Omniclip media controller
 * @returns True if file exists
 */
export async function mediaExistsInEngine(
  mediaId: string,
  mediaController: Media
): Promise<boolean> {
  const hash = getFileHash(mediaId);
  
  if (!hash) {
    return false;
  }

  const file = await mediaController.get_file(hash);
  return !!file;
}

